apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: decider-app-1
  # namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mygithub23/k8s-decider.git
    targetRevision: HEAD
    path: k8s-decider
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true