services:
  web:
    depends_on:
      db:
        condition: service_healthy
    image: madkar777/decider-web
    restart: always 
    ports:
      - "8001:5000"
    environment:
      FULL_BUILD_MODE: preserve
      DB_HOSTNAME: db
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: decider
      DB_PORT: 5432
      ADMIN_EMAIL: admin@admin.com
      ADMIN_PASS: admin
      WEB_HTTPS_ON: 
      CART_ENC_KEY: 12345678901234567890123456789012
    networks:
      - app-network
  db:
    image: "madkar777/decider-db"
    restart: always 
    ports:
      - "5432"
    environment:
      # - GET_HOSTS_FROM=dns
      POSTGRES_INITDB_ARGS: '--auth=md5'
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_USER: user
      PGUSER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: decider     
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
       - db_data:/var/lib/postgresql/data
    networks:
      - app-network  
    labels:
       - kompose.service.type:LoadBalancer      

networks:
  app-network:
    driver: bridge
           
volumes:
  db_data:
