apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  # namespace: decider-ns
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
