apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component.service: db-data
  name:  debs-postgres-claim
spec:
  storageClassName: manual # ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
status: {}