apiVersion: apps/v1
kind: Deployment
metadata:
  name: decider-web
  labels:
    app: decider-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: decider-web
  strategy: {}
  template:
    metadata:
      labels:
        app: decider-web
    spec:
      containers:
        - name: decider-web
          image: madkar777/decider-web:v4
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              memory: 1024Mi
              cpu: 1
          env:
            - name: FULL_BUILD_MODE
              value: preserve
            - name: DB_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: DB_HOSTNAME
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: DB_USERNAME                  
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: DB_PASSWORD
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: DB_PORT
            - name: ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: ADMIN_EMAIL                  
            - name: ADMIN_PASS
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: ADMIN_PASS                  
            - name: CART_ENC_KEY
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: CART_ENC_KEY
            - name: WEB_HTTPS_ON
              valueFrom:
                configMapKeyRef:
                  name: env-configmap
                  key: WEB_HTTPS_ON                                    